name: Build

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - feature/*
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Generate APK
      run: ./gradlew --no-daemon build
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        path: app/build/outputs/apk/debug/app-debug.apk